import { commonDefinition, simpleRowsWithDefault } from "./common-master-definitions";
import { createCommonMasterSeeder } from "./common-master-seeder";

export const contactsCommonSeeders = [
  createCommonMasterSeeder(
    commonDefinition("contactGroups"),
    60,
    simpleRowsWithDefault([
      ["CUST", "Customer"],
      ["ECOM-CUST", "Ecommerce Customer"],
      ["COLD-CUST", "Cold Customer"],
      ["VEND", "Vendor"],
      ["STAFF", "Staff"],
      ["LABOUR", "Labour"],
      ["MANAGER", "Manager"],
      ["SUPPLIER", "Supplier"],
      ["AGENT", "Agent"],
      ["TRANSPORTER", "Transporter"],
    ]),
  ),
  createCommonMasterSeeder(
    commonDefinition("contactTypes"),
    61,
    simpleRowsWithDefault([
      ["SUNDRY-CR", "Sundry Creditors"],
      ["SUNDRY-DR", "Sundry Debtors"],
      ["PRIMARY", "Primary"],
      ["BILLING", "Billing"],
      ["SHIPPING", "Shipping"],
      ["ACCOUNTS", "Accounts"],
      ["PURCHASE", "Purchase"],
      ["SALES", "Sales"],
    ]),
  ),
  createCommonMasterSeeder(
    commonDefinition("addressTypes"),
    62,
    simpleRowsWithDefault([
      ["BILL", "Billing"],
      ["SHIP", "Shipping"],
      ["PRIMARY", "Primary"],
      ["SECONDARY", "Secondary"],
      ["THIRD", "Third"],
    ]),
  ),
  createCommonMasterSeeder(
    commonDefinition("bankNames"),
    63,
    simpleRowsWithDefault([
      ["SBI", "State Bank of India"],
      ["HDFC", "HDFC Bank"],
      ["ICICI", "ICICI Bank"],
      ["AXIS", "Axis Bank"],
      ["KOTAK", "Kotak Mahindra Bank"],
      ["PNB", "Punjab National Bank"],
      ["BOB", "Bank of Baroda"],
      ["CANARA", "Canara Bank"],
      ["UNION", "Union Bank of India"],
      ["BOI", "Bank of India"],
      ["INDIAN", "Indian Bank"],
      ["IOB", "Indian Overseas Bank"],
      ["CBI", "Central Bank of India"],
      ["UCO", "UCO Bank"],
      ["BOM", "Bank of Maharashtra"],
      ["PSB", "Punjab and Sind Bank"],
      ["IDBI", "IDBI Bank"],
      ["YES", "Yes Bank"],
      ["IDFC", "IDFC First Bank"],
      ["FEDERAL", "Federal Bank"],
      ["SIB", "South Indian Bank"],
      ["KVB", "Karur Vysya Bank"],
      ["CUB", "City Union Bank"],
      ["TMB", "Tamilnad Mercantile Bank"],
      ["DCB", "DCB Bank"],
      ["RBL", "RBL Bank"],
      ["BANDHAN", "Bandhan Bank"],
      ["CSB", "CSB Bank"],
      ["DHAN", "Dhanlaxmi Bank"],
      ["JKB", "Jammu and Kashmir Bank"],
      ["KBL", "Karnataka Bank"],
      ["AUBANK", "AU Small Finance Bank"],
      ["EQUITAS", "Equitas Small Finance Bank"],
      ["UJJIVAN", "Ujjivan Small Finance Bank"],
      ["ESAF", "ESAF Small Finance Bank"],
      ["FINCARE", "Fincare Small Finance Bank"],
      ["JANA", "Jana Small Finance Bank"],
      ["SURYODAY", "Suryoday Small Finance Bank"],
      ["UTKARSH", "Utkarsh Small Finance Bank"],
      ["NSDL", "NSDL Payments Bank"],
      ["AIRTELPB", "Airtel Payments Bank"],
      ["INDIAPOSTPB", "India Post Payments Bank"],
      ["FINO", "Fino Payments Bank"],
    ]),
  ),
] as const;
