import type { CompanyRecord } from "../../domain/company-record";

export type CompanyResponse = ReturnType<typeof toCompanyResponse>;

export function toCompanyResponse(company: CompanyRecord) {
  return {
    id: company.id,
    tenantId: company.tenantId,
    tenantName: company.tenantName,
    industryId: company.industryId,
    industryCode: company.industryCode,
    industryName: company.industryName,
    code: company.code,
    name: company.name,
    legalName: company.legalName,
    tagline: company.tagline,
    shortAbout: company.shortAbout,
    gstinUin: company.gstinUin,
    pan: company.pan,
    dateOfIncorporation: company.dateOfIncorporation,
    msmeNo: company.msmeNo,
    msmeCategory: company.msmeCategory,
    tan: company.tan,
    tdsAvailable: company.tdsAvailable,
    tdsSection: company.tdsSection,
    tdsRatePercent: company.tdsRatePercent,
    tcsAvailable: company.tcsAvailable,
    tcsSection: company.tcsSection,
    tcsRatePercent: company.tcsRatePercent,
    website: company.website,
    description: company.description,
    primaryEmail: company.primaryEmail,
    primaryPhone: company.primaryPhone,
    isPrimary: company.isPrimary,
    isActive: company.isActive,
    createdAt: company.createdAt.toISOString(),
    updatedAt: company.updatedAt.toISOString(),
    deletedAt: company.deletedAt ? company.deletedAt.toISOString() : null,
    logos: company.logos,
    addresses: company.addresses,
    emails: company.emails,
    phones: company.phones,
    socialLinks: company.socialLinks,
    bankAccounts: company.bankAccounts,
  };
}
