import type { ProductRecord, ProductUpsertInput } from "./product";

export function createDefaultProductFormValues(): ProductUpsertInput {
  return {
    code: "",
    name: "",
    slug: "",
    description: null,
    shortDescription: null,
    brandId: null,
    brandName: null,
    categoryId: null,
    categoryName: null,
    productGroupId: null,
    productGroupName: null,
    productTypeId: null,
    productTypeName: null,
    unitId: null,
    hsnCodeId: null,
    styleId: null,
    sku: "",
    hasVariants: false,
    basePrice: 0,
    costPrice: 0,
    taxId: null,
    isFeatured: false,
    isActive: true,
    storefrontDepartment: null,
    isNewArrival: false,
    isBestSeller: false,
    isFeaturedLabel: false,
    images: [],
    variants: [],
    prices: [],
    discounts: [],
    offers: [],
    attributes: [],
    attributeValues: [],
    variantMap: [],
    stockItems: [],
    stockMovements: [],
    seo: null,
    storefront: null,
    tags: [],
    reviews: [],
  };
}

export function toProductFormValues(product: ProductRecord): ProductUpsertInput {
  return {
    ...createDefaultProductFormValues(),
    code: product.code,
    name: product.name,
    slug: product.slug,
    description: product.description,
    shortDescription: product.shortDescription,
    brandId: product.brandId,
    brandName: product.brandName,
    categoryId: product.categoryId,
    categoryName: product.categoryName,
    productGroupId: product.productGroupId,
    productGroupName: product.productGroupName,
    productTypeId: product.productTypeId,
    productTypeName: product.productTypeName,
    unitId: product.unitId,
    hsnCodeId: product.hsnCodeId,
    styleId: product.styleId,
    sku: product.sku,
    hasVariants: product.hasVariants,
    basePrice: product.basePrice,
    costPrice: product.costPrice,
    taxId: product.taxId,
    isFeatured: product.isFeatured,
    isActive: product.isActive,
    storefrontDepartment: product.storefrontDepartment,
    isNewArrival: product.isNewArrival,
    isBestSeller: product.isBestSeller,
    isFeaturedLabel: product.isFeaturedLabel,
    images: product.images,
    variants: product.variants,
    prices: product.prices,
    discounts: product.discounts,
    offers: product.offers,
    attributes: product.attributes,
    attributeValues: product.attributeValues,
    variantMap: product.variantMap,
    stockItems: product.stockItems,
    stockMovements: product.stockMovements,
    seo: product.seo,
    storefront: product.storefront,
    tags: product.tags,
    reviews: product.reviews,
  };
}
