name: ${COMPOSE_PROJECT_NAME:-cxnext-client}

services:
  app:
    build:
      context: ../..
      dockerfile: .container/Dockerfile
      args:
        BACKEND_HEALTH_URL: ${BACKEND_HEALTH_URL}
        BACKEND_URL: ${BACKEND_URL}
        FRONTEND_URL: ${FRONTEND_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_SETUP_LOOKUP_ENABLED: ${NEXT_PUBLIC_SETUP_LOOKUP_ENABLED:-false}
    image: cxnext:${APP_VERSION:-v1}
    container_name: ${APP_CONTAINER_NAME:-app}
    restart: unless-stopped
    env_file:
      - path: ${CLIENT_ENV_FILE:-./codexsun/client.env}
        required: true
    environment:
      NODE_ENV: production
      PORT: ${APP_HTTP_PORT:-4000}
    ports:
      - "${FRONTEND_PUBLIC_PORT:-3000}:3000"
      - "${APP_PUBLIC_PORT:-4000}:4000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ${DEPLOY_SOURCE:-../..}
        target: /deploy/cxnext
    networks:
      - codexion-network

networks:
  codexion-network:
    name: codexion-network
    external: true
